### ISSUE TITLE
GET API

### ISSUE THREAD

**Issue by Codingboy** [Aqarius90/FA_WG_Ulilities#17]
It would be awesome if I could redirect users from my page to yours to see the deck without copy paste it.
Is it possible to show a deck if your page is called like this:
https://aqarius90.github.io/FA_WG_Utilities/?deck='@Ho8J2ggcyPWcRU6ZKUlhEBvA1GALQDAJkpgEzwG4YuVBEHpKKWxxZyKiVxBH6JMQfBZqWAFYhZJR8i9knsWWiClQiKAieFKKJaA='
Or is there a way to remote set the data like: (I am a really js noob)
```
                <script>\n\
                        function blub()\n\
                        {\n\
                                document.getElementById('sDeckString').value = '@Ho8J2ggcyPWcRU6ZKUlhEBvA1GALQDAJkpgEzwG4YuVBEHpKKWxxZyKiVxBH6JMQfBZqWAFYhZJR8i9knsWWiClQiKAieFKKJaA=';\n\
                        }\n\
                        function bla(){\n\
                                var newWin = window.open('https://aqarius90.github.io/FA_WG_Utilities/');\n\
                                newWin.onload = blub();\n\
                        }\n\
                </script>\n\
                <script>document.onload = bla();</script>\n\
```

**Comment by Aqarius90** [comment]
Good idea.

*some stackoverflow later*

done:
https://aqarius90.github.io/FA_WG_Utilities/?=@Ho8J2ggcyPWcRU6ZKUlhEBvA1GALQDAJkpgEzwG4YuVBEHpKKWxxZyKiVxBH6JMQfBZqWAFYhZJR8i9knsWWiClQiKAieFKKJaA=

**Comment by Codingboy** [comment]
thanks! awesome tool btw!
