### ISSUE TITLE
Steel Division Port?

### ISSUE THREAD

**Issue by Dehorser** [Aqarius90/FA_WG_Ulilities#18]
Do you mind if I fork this to make a Steel Division deck builder?

**Comment by Aqarius90** [comment]
Just put this up yesterday: https://aqarius90.github.io/FASDDB/index.html

Mind, there's no data extractor tool that I could find, so It's missing unit pictures and weapons data, but those could be added. There's even a CSV parser for auto updating that I wrote for a WRD branch that I never finished. 

If you feel like taking a crack at it, be my guest.

**Comment by Aqarius90** [comment]
Well, after some fiddling, we now have feature parity:
https://aqarius90.github.io/SteelDivisionDB/
There's still a few things to fix, but I'd say this particular issue is closed.
